### ISSUE TITLE
TapToAccess error on tap

### ISSUE THREAD

**Issue by pnogier** [kisi-inc/kisi-ios-st2u-framework#12]
Hi there, 

We are currently working on implementing the Tap To Access feature in our React Native app.
We created a NativeModule to use it within our RN code. 

Basically we just initialize the module with the credentials we get when we login on behalf of the user, then we set it in an AuthStorage module.
Then we return the Login object in the `tapToAccessLoginForOrganization`, but when tapping the device against the reader, we are getting an error: `SecureAccess.TapToAccessError.failedToVerifyReaderProof` 

I might obviously be missing something or doing something wrong, did anyone encountered this issue ? 

Thanks in advance

**Comment by mikaoj** [comment]
Chances are that you are returning the wrong data in the Login object

**Comment by pnogier** [comment]
Hi @mikaoj,

Thanks for your answer, indeed I was using a wrong ID in the Login object. 

Fixed and working now.
