### ISSUE TITLE
[QUESTION] SDK usage when app is closed

### ISSUE THREAD

**Issue by pnogier** [kisi-inc/kisi-ios-st2u-framework#14]
Hi there, 

We recently implemented the SDK into our React Native mobile app. 
So basically we require the user to do a specific action on our app so the SDK is initialized with its proper login information, then he can unlock its doors. 
Everything is working properly so far, but the doors won't unlock if the app is killed.

Is this the expected behaviour ? Or am I missing something important to make it work when the app is killed ?

**Comment by ce07c3** [comment]
Hi! When the app is killed, iOS may not wake the upp app right away. Not killing the app is the way to go.

**Comment by pnogier** [comment]
Hi @ce07c3 !

Thank you for your answer !
We talked to our client and from what he says, he can unlock his locks using the Kisi app even when killed, so we were wondering what are the differences between how the Kisi app works and the iOS SDK

**Comment by ce07c3** [comment]
Well, it usually works _eventually_, but it can take time before the app wakes up again. Our iOS SDK should come "with batteries included". It would make sense for us to explain this more in-depth. I will ask the team to get back, but it may take a bit of time since it's vacation time. 😆

**Comment by mikaoj** [comment]
You need to request location permission and monitor for readers, as shown in the README and the example app.
