### ISSUE TITLE
How do you connect this to a users Kisi account?

### ISSUE THREAD

**Issue by JWPersh** [kisi-inc/kisi-ios-st2u-framework#3]
We cannot see where to pass the users credentials to gain access.

**Comment by mikaoj** [comment]
I don’t understand your issue, is there any way you could explain it a bit more so I hopefully can help you?

**Comment by mikaoj** [comment]
Are you expecting to pass in email/password for a user in this framework?

**Comment by JWPersh** [comment]
Yes, or some kind of authentication_token token? Essentially, something like the auth in the Kisi API. Or am I misunderstanding how this framework works? Does a user already have to have the Kisi app on their phone for us to use this framework?

**Comment by mikaoj** [comment]
So this framework is limited to the scope of handling the communication between our readers and the phone, to enable you to build an app that provides the same type of tap to unlock that the Kisi app does.

You are expected to handle everything with signing in users and handling communication with the Kisi API.
And once you've done that there are a number of callbacks from this framework that you need to respond to, like the login id, key, certificate that you get when you sign in a user.
See documentation in the README.

**Comment by ocs-sport** [comment]
Thanks mikaoj, this makes sense. I don't suppose you have an example application using this framework?

**Comment by mikaoj** [comment]
No, but it might be something we could add at some point.

But if you encounter any problems, you can create an issue here or email me if you need help to get going. 
joakim at kiso dot io
