### ISSUE TITLE
When will it use location in the background

### ISSUE THREAD

**Issue by quoait** [kisi-inc/kisi-ios-st2u-framework#4]
How it improves the performance of tap to unlock? 
Under what conditions will it use background location service, how long will it continue use location service, and will it consume a lot of power?

**Comment by ce07c3** [comment]
- To listen for BLE advertisements
- Whenever it is called by iOS due to nearby beacon matches
- Same as above
- No, we don't even see it in battery statistics most of the time

**Comment by quoait** [comment]
Hi @ce07c3 

https://www.getkisi.com/academy/lessons/how-to-use-ios-mobile-unlocking

From the above document, it is said that iOS app broadcast iBeacon signal, the reader receives the signal and pinpoint whether the particular iPhone is in range, and then connect to iPhone BLE for door unlock.

Since iOS app is acting as an BLE peripheral, why it need to listen for BLE advertisements?

**Comment by ce07c3** [comment]
The article is outdated. The current implementation is not using iBeacons for unlocks, just for proximity checks to satisfy restrictions.

**Comment by quoait** [comment]
@mikaoj @ce07c3  Thank you for the clarifications. 

>The phone will monitor the for iBeacons that the reader advertises. So when the phone is nearby the reader it will start the app in background and be ready to perform unlocks over BLE.

Does the Reader advertising iBeacon all the time or only when the phone is nearby it?
Yes, the phone requires `Allways Allowed` location permission to monitor for iBeacons. But i don't think app requires location in `UIBackgroundModes` since app doesn't use location service(gps). 


>Without location permission we have to rely on iOS starting the app based on the BLE service it advertises.
Which in our tests have been slower and sometimes doesn't happen at all.

Tap to Unlock can take several seconds or even fail without  always location permission. Please correct me if i am wrong.

**Comment by mikaoj** [comment]
The reader always advertises an iBeacon.

Correct, location background mode isn't necessary. I have a pending update to the README that will clarify that which will be released sometime when I get back from my vacation.

> Tap to Unlock can take several seconds or even fail without always location permission. Please correct me if i am wrong.

Correct.

**Comment by quoait** [comment]
@mikaoj Thanks again, the last question.

>The reader always advertises an iBeacon.

An iBeacon can wake up app in the background, but only gets to run for about five to ten seconds in the background before being suspended again. Does it mean that after I approach the door, I have to put my phone close to the reader to unlock the door within ten seconds, otherwise it won't work? When the phone is Tap to the reader, will the reader broadcast another ibeacon to wake up the app?

**Comment by mikaoj** [comment]
No it should work for longer periods than 10 seconds.
And yes we have some measures in place to "wake" the app up in case you are within beacon range for long periods of time.
