### ISSUE TITLE
tapToAccessSuccess fires when loging in

### ISSUE THREAD

**Issue by AngeloMateus** [kisi-inc/kisi-ios-st2u-framework#5]
After a Login created event the function gets triggered before the unlock or green light on the reader, this causes our application to display an unlock success message without an actual unlock.

**Comment by mikaoj** [comment]
The callback indicates if the phone and reader finished the tap to access communication.
Then it's up to API or, in case of an offline unlock, the controller to grant or deny the unlock request. The phone knows nothing about that.

I would advice against showing anything to the user inside the app, for above mentioned reason, thats what the leds on the reader are for :)

**Comment by AngeloMateus** [comment]
The comment under that method is         // Callback when unlock succeeds.
Can this be changed if it is not the correct behaviour.

**Comment by mikaoj** [comment]
Sure
