### ISSUE TITLE
Missing package product 'SecureUnlock'

### ISSUE THREAD

**Issue by GnSoloinsight** [kisi-inc/kisi-ios-st2u-framework#6]
I am facing this problem after resolving my Package Dependencies in Example Project.

here is my xcode image

![XCodeError](https://user-images.githubusercontent.com/113498095/190082199-6af35201-c417-468d-bd68-62f2a6b9c94c.png)

Anyone faced this issue while using kisi ?

**Comment by mikaoj** [comment]
Check out master. The Example was updated for 0.5.0 (which renamed SecureUnlock to SecureAccess) after 0.5.0 was tagged.

**Comment by mikaoj** [comment]
And since it looks like you have downloaded a zip of the repo and are new at github here is a link to download master as a zip: https://github.com/kisi-inc/kisi-ios-st2u-framework/archive/refs/heads/master.zip
